language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - python setup.py install
  - git clean -xfd
# command to run tests
script:
  - python run_tests.py
