cmd_name: commands.csv
csv_directory: /Users/koer2434/Google Drive/UST/research/instrbuilder/instruments
lookup_name: lookup.csv
instruments:
  mso_scope:
    address:
      pyvisa: USB0::0x0957::0x17A9::MY52160418::INSTR
    csv_folder: /keysight/oscilloscope/MSOX3000
    python_class: KeysightMSOX3000
  new_function_gen:
    address:
      pyvisa: USB0::0x0957::0x2B07::MY57700733::INSTR
    csv_folder: /keysight/function_gen/33500B/
    python_class: AgilentFunctionGen
  srs_lockin:
    address:
      pyserial: /dev/tty.USA19H141113P1.1
    address_can_change: true
    csv_folder: /srs/lock_in/sr810/
    python_class: SRSLockIn
  my_multi:
    python_class: Multimeter
    csv_folder: /key/dmm/test
